# backend/Dockerfile.dev
FROM python:3.14-slim

WORKDIR /app

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

ENV UV_LINK_MODE=copy \
    UV_COMPILE_BYTECODE=1 \
    PYTHONUNBUFFERED=1

COPY pyproject.toml uv.lock ./

# installs dependencies only (no project code)
RUN uv sync --locked --no-install-project

COPY app ./app

# installs project code into the venv
RUN uv sync --locked

ENV PATH="/app/.venv/bin:$PATH"

EXPOSE 8000
#CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
